name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.0", "3.1", "3.2"]
        gemfile: ['Gemfile']
        include:
        - ruby: "3.0"
          gemfile: "gemfiles/newrelic-7.gemfile"
        - ruby: "3.1"
          gemfile: "gemfiles/newrelic-8.gemfile"

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
    - uses: actions/checkout@v3.5.3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle install
    - run: bundle exec rspec
